### ISSUE TITLE
Alembic/Util/Foundation.h:66 half.h not found

### ISSUE THREAD

**Issue by enziop** [hsab/UMOG#7]
Hi, i first tried building on Windows 10 with anaconda and VS17 and now on archlinux but get the same error on both

am i missing something? I have alembic, ilmbase and openexr installed on archlinux
half.h should be part of ilmbase if i'm guessing right

greetings
enzio

Error:
`[enzio@xps-karch UMOG]$ umog_addon/packages/install.sh 
Collecting pyglet
  Using cached pyglet-1.3.0-py2.py3-none-any.whl
Collecting future (from pyglet)
  Using cached future-0.16.0.tar.gz
Installing collected packages: future, pyglet
  Running setup.py install for future ... done
Successfully installed future-0.16.0 pyglet-1.3.0
Collecting PyMCubes
  Using cached PyMCubes-0.0.6.tar.gz
Installing collected packages: PyMCubes
  Running setup.py install for PyMCubes ... done
Successfully installed PyMCubes-0.0.6
Collecting cymem
  Using cached cymem-1.31.2.tar.gz
Installing collected packages: cymem
  Running setup.py install for cymem ... done
Successfully installed cymem-1.31.2
[enzio@xps-karch UMOG]$ python setup.py --noversioncheck --pyximport
Unknown arguments: {'--pyximport'}
Allowed arguments: {'--export', '--noversioncheck', '--nocopy', '--all'}
[enzio@xps-karch UMOG]$ python setup.py --noversioncheck            
3.6.4 (default, Dec 23 2017, 19:07:07) 
[GCC 7.2.1 20171128]

Removed from sys.path: /usr/share/blender/2.79/scripts/addons_contrib/UMOG
running build_ext
building 'umog_addon.engine.engine.alembic' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /usr/share/blender/2.79/scripts/addons_contrib/UMOG/umog_addon/engine/engine/alembic.cpp -o build/temp.linux-x86_64-3.6/usr/share/blender/2.79/scripts/addons_contrib/UMOG/umog_addon/engine/engine/alembic.o -I/usr/local/include/OpenEXR -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from /usr/include/Alembic/Util/All.h:40:0,
                 from /usr/include/Alembic/AbcCoreAbstract/Foundation.h:40,
                 from /usr/include/Alembic/AbcCoreAbstract/ArchiveReader.h:41,
                 from /usr/include/Alembic/AbcCoreAbstract/All.h:40,
                 from /usr/include/Alembic/Abc/Foundation.h:40,
                 from /usr/include/Alembic/Abc/Base.h:40,
                 from /usr/include/Alembic/Abc/All.h:40,
                 from /usr/share/blender/2.79/scripts/addons_contrib/UMOG/umog_addon/engine/engine/alembic.cpp:477:
/usr/include/Alembic/Util/Foundation.h:66:10: fatal error: half.h: No such file or directory
 #include <half.h>
          ^~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1`

**Comment by mp4** [comment]
Just updated the setup.py file the plugin should now build on arch.
Let me know if this still is failing for you on arch.

**Comment by mp4** [comment]
I also updated the build instructions for arch on the wiki.

**Comment by enziop** [comment]
ok, it builds all fine now, but when enabling the addon it says it couldn't find _mcubes
i looked in the installation log of setup.sh where it says "Successfully installed PyMCubes-0.0.6"


`FAILED TO LOAD  .engine.engine.engine umog_addon
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/__init__.py", line 106, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], 'umog_addon')
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/import_modules.py", line 11, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "umog_addon/engine/engine/engine.pyx", line 26, in init umog_addon.engine.engine.engine (/home/enzio/software/UMOG/umog_addon/engine/engine/engine.c:46935)
    from . import reaction_diffusion_gpu
  File "umog_addon/engine/engine/reaction_diffusion_gpu.pyx", line 19, in init umog_addon.engine.engine.reaction_diffusion_gpu (/home/enzio/software/UMOG/umog_addon/engine/engine/reaction_diffusion_gpu.c:24990)
    from ...packages import mcubes
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/packages/mcubes/__init__.py", line 2, in <module>
    from ._mcubes import marching_cubes, marching_cubes_func
ModuleNotFoundError: No module named 'umog_addon.packages.mcubes._mcubes'`


further info:
`[enzio@xps-karch mcubes]$ cd /usr/share/blender/2.79/scripts/addons_contrib/umog_addon/packages/mcubes/
[enzio@xps-karch mcubes]$ ls -a
.  ..  exporter.py  __init__.py  __pycache__
[enzio@xps-karch mcubes]$ cat __init__.py 

from ._mcubes import marching_cubes, marching_cubes_func
from .exporter import export_mesh, export_obj, export_off
`

**Comment by enziop** [comment]
I guessed it to be a typo and changed "from ._mcubes import" to "from mcubes import", now it throws a different error when enabling the addon:

`FAILED TO LOAD  .engine.nodes.algorithm.pyglet_3dRD umog_addon
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/__init__.py", line 106, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], 'umog_addon')
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/import_modules.py", line 11, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/engine/nodes/__init__.py", line 1, in <module>
    from .engine_node import EngineNode, EngineIntputNode, EngineOutputNode
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/engine/nodes/engine_node.py", line 117, in <module>
    class EngineBinaryScalarNode(EngineNode):
  File "/usr/share/blender/2.79/scripts/addons_contrib/umog_addon/engine/nodes/engine_node.py", line 121, in EngineBinaryScalarNode
    opcode = engine.NOP
AttributeError: module 'umog_addon.engine.engine.engine' has no attribute 'NOP'`

**Comment by mp4** [comment]
No change that line back often/always pymcubes doesn't install all the way the first time it is installed.(I was hoping the package would resolve this itself) The important file that doesn't always install is  mcubes/_mcubes.cpython-36m-x86_64-linux-gnu.so.
Go to the packages folder and run pip install PyMCubes -t . --upgrade. Check after running this command if mcubes/_mcubes.cpython-36m-x86_64-linux-gnu.so has installed, if it has continue building the plugin otherwise run this command a few more times to see if it will produce the needed file, then if not get me the output of the above command. Let me know how this goes.

**Comment by enziop** [comment]
in umog_addon/packages/install.sh i added --upgrade to all 3 lines
before pip complained that the folders already exist and didnt install the packages
now everything works
thank you

**Comment by mp4** [comment]
Cool. I'll close this issue.
